variable "cidr_block" {}
variable "availability_zones" {}
variable "env" {}
variable "default_vpc_id" {}
variable "vpc_id" {}
variable "vpc_peering_connection_id" {}
variable "internet_gw" {}
variable "nat_gw" {}
variable "name" {}
variable "internet_gw_id" {}
